#!/bin/bash
set -e

DEST=$1
BINARY_NAME="docker$2-$VERSION"
BINARY_EXTENSION="$(binary_extension)"
BINARY_FULLNAME="$BINARY_NAME$BINARY_EXTENSION"

# Cygdrive paths don't play well with go build -o.
if [[ "$(uname -s)" == CYGWIN* ]]; then
	DEST=$(cygpath -mw $DEST)
fi

source "${MAKEDIR}/.go-autogen"

echo "Building: $DEST/$BINARY_FULLNAME"
go build \
	-o "$DEST/$BINARY_FULLNAME" \
	"${BUILDFLAGS[@]}" \
	-ldflags "
		$LDFLAGS
		$LDFLAGS_STATIC_DOCKER
	" \
	./docker

if [ -n "$2" ]; then
	ln -sf "$BINARY_FULLNAME" "$DEST/docker$BINARY_EXTENSION"
	hash_files "$DEST/$BINARY_FULLNAME"
fi


